<a href="https://colab.research.google.com/github/shuvo1165/Machine-Learning/blob/main/Understanding_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

0 Dimansional Tensor (Scaler)

In [2]:
import numpy as np
a = np.array(12)
a

array(12)

In [3]:
a.ndim

0

1 Diamentional Tensor (Vector)

In [4]:
b = np.array([12,1,4,5,11])
b

array([12,  1,  4,  5, 11])

In [5]:
b.ndim

1

2 Dimantional Tensor (Matrix)

In [6]:
c = np.array([[2,4,6,22],
              [11,32,2,3],
              [23,76,8,9]])
c

array([[ 2,  4,  6, 22],
       [11, 32,  2,  3],
       [23, 76,  8,  9]])

In [7]:
c.ndim

2

3 Dimensional Tensor

In [8]:
d = np.array([[[1,2,3],
               [4,5,6],
               [1,3,4]],
              [[2,4,5],
               [3,4,7],
               [9,0,5]]])
d

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 3, 4]],

       [[2, 4, 5],
        [3, 4, 7],
        [9, 0, 5]]])

In [9]:
d.ndim

3

Tensor Matrix Multiplication

In [2]:
import tensorflow as tf

In [4]:
e = tf.constant([[3,7],
                [1,9]])
f = tf.constant([[5],[2]])
ef = tf.matmul(e,f)
print(('"e" "f"\n{0}').format(ef))

"e" "f"
[[29]
 [23]]


MNIST Dataset Understraning

In [5]:
from tensorflow import keras
fashion_mnist = tf.keras.datasets.fashion_mnist
(Training_Image, Training_Lebel) , (Test_Image , Test_Lebel) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [6]:
print(Training_Image.ndim)

3


In [7]:
print(Training_Image.shape)

(60000, 28, 28)
